name = "Sacabambaspis"
uuid = "3441b350-8fbf-4fad-b964-2debb0b6d63a"
authors = ["Satoshi Terasaki <terasakisatoshi.math@gmail.com> and contributors"]
version = "1.0.0-DEV"


[compat]
julia = "1.8"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
JET = "c3a54625-cd67-489e-a8e7-0a5a0ff4e31b"
ReTestItems = "817f1d60-ba6b-4fd5-9520-3cf149f6a823"
ReferenceTests = "324d217c-45ce-50fc-942e-d289b448e8cf"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "JET", "Test", "ReferenceTests", "ReTestItems"]
